config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/transaction.rb
class Transaction < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:book_name, :author_name, :isbn_code, :number_of_books, :publish_date, :book_category, :number_of_books_issued)
    end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:book_id, :transaction_date, :transaction_type, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/books/_form.html.erb
<%= form_for(book) do |f| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :book_name %>
    <%= f.text_field :book_name %>
  </div>

  <div class="field">
    <%= f.label :author_name %>
    <%= f.text_field :author_name %>
  </div>

  <div class="field">
    <%= f.label :isbn_code %>
    <%= f.number_field :isbn_code %>
  </div>

  <div class="field">
    <%= f.label :number_of_books %>
    <%= f.number_field :number_of_books %>
  </div>

  <div class="field">
    <%= f.label :publish_date %>
    <%= f.number_field :publish_date %>
  </div>

  <div class="field">
    <%= f.label :book_category %>
    <%= f.text_field :book_category %>
  </div>

  <div class="field">
    <%= f.label :number_of_books_issued %>
    <%= f.text_field :number_of_books_issued %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<div ng-app="BookApp">
  <div ng-controller="indexController">
    <div ui-grid="gridOptions" class="bookGrid">
    </div>
  </div>
</div>


<table class= "table bordered table">
  <thead>
    <tr>
      <th>Book Name</th>
      <th>Author Name</th>
      <th>ISBN Code</th>
      <th>Number of Books</th>
      <th>Publish Date</th>
      <th>Book Category</th>
      <th>Number of Books Issued</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.book_name %></td>
        <td><%= book.author_name %></td>
        <td><%= book.isbn_code %></td>
        <td><%= book.number_of_books %></td>
        <td><%= book.publish_date %></td>
        <td><%= book.book_category %></td>
        <td><%= book.number_of_books_issued %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button><%= link_to 'New Book', new_book_path %></button>

<h1>Transactions</h1>

<table class= "table bordered table">
  <thead>
    <tr>
      <th>Book</th>
      <th>Transaction Date</th>
      <th>Transaction Type</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>


<button><%= link_to 'New Transaction', new_transaction_path %></button>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Book name:</strong>
  <%= @book.book_name %>
</p>

<p>
  <strong>Author name:</strong>
  <%= @book.author_name %>
</p>

<p>
  <strong>Isbn code:</strong>
  <%= @book.isbn_code %>
</p>

<p>
  <strong>Number of books:</strong>
  <%= @book.number_of_books %>
</p>

<p>
  <strong>Publish date:</strong>
  <%= @book.publish_date %>
</p>

<p>
  <strong>Book category:</strong>
  <%= @book.book_category %>
</p>

<p>
  <strong>Number of books issued:</strong>
  <%= @book.number_of_books_issued %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="myapplication">
  <head>
    <title>Booktastic</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>

    <body>
      <div class="container" ng-view>
    <!-- <body data-no-turbolink> -->
    <%= yield %>
      </div>
  </body>
</html>

app/views/transactions/_form.html.erb
<%= form_for(transaction) do |f| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :book_id %>
    <%= f.number_field :book_id %>
  </div>

  <div class="field">
    <%= f.label :transaction_date %>
    <%= f.number_field :transaction_date %>
  </div>

  <div class="field">
    <%= f.label :transaction_type %>
    <%= f.number_field :transaction_type %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.number_field :date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transactions</h1>

<table class="table border table">
  <thead>
    <tr>
      <th>Book</th>
      <th>Transaction date</th>
      <th>Transaction type</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.book_id %></td>
        <td><%= transaction.transaction_date %></td>
        <td><%= transaction.transaction_type %></td>
        <td><%= transaction.date %></td>
        <td><%= link_to 'Show', transaction %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Book:</strong>
  <%= @transaction.book_id %>
</p>

<p>
  <strong>Transaction date:</strong>
  <%= @transaction.transaction_date %>
</p>

<p>
  <strong>Transaction type:</strong>
  <%= @transaction.transaction_type %>
</p>

<p>
  <strong>Date:</strong>
  <%= @transaction.date %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>